name: docker

on:
  pull_request: [c4t, dev]
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - id: branchVars
        name: Evaluate branch
        run: |
          if [[ ${{ github.event_name }} != workflow_dispatch ]]; then
            echo "ref=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.inputs.wd_branch }}" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branchVars.outputs.ref }}
          fetch-depth: 0
      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_pass }}
      - name: Set tag variables
        id: setTagVariables
        run: |
          if [[ ${{ github.ref_type }} == tag ]]; then
            echo "version=stable-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            echo "version=unstable-${BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            c4tplatform/camino-wallet:${{ steps.setTagVariables.outputs.version }}
          push: false
